// Kenya's 47 counties — used to offer a pick-list instead of free text.
export const KENYA_COUNTIES: readonly string[] = [
  "Baringo",
  "Bomet",
  "Bungoma",
  "Busia",
  "Elgeyo Marakwet",
  "Embu",
  "Garissa",
  "Homa Bay",
  "Isiolo",
  "Kajiado",
  "Kakamega",
  "Kericho",
  "Kiambu",
  "Kilifi",
  "Kirinyaga",
  "Kisii",
  "Kisumu",
  "Kitui",
  "Kwale",
  "Laikipia",
  "Lamu",
  "Machakos",
  "Makueni",
  "Mandera",
  "Marsabit",
  "Meru",
  "Migori",
  "Mombasa",
  "Murang'a",
  "Nairobi",
  "Nakuru",
  "Nandi",
  "Narok",
  "Nyamira",
  "Nyandarua",
  "Nyeri",
  "Samburu",
  "Siaya",
  "Taita Taveta",
  "Tana River",
  "Tharaka Nithi",
  "Trans Nzoia",
  "Turkana",
  "Uasin Gishu",
  "Vihiga",
  "Wajir",
  "West Pokot",
];

// Place types are a fixed taxonomy: the routing model and the zone-id scheme
// (CBD/STG/RES) both depend on these three categories.
export const ZONE_TYPE_OPTIONS: ReadonlyArray<{ value: string; label: string }> = [
  { value: "stage", label: "Stage" },
  { value: "cbd_hub", label: "Town centre hub" },
  { value: "residential_area", label: "Residential area" },
];
