/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List supported drop-off / pick-up locations */
        get: operations["listZones"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/zones/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search locations by name */
        get: operations["searchZones"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get delivery options and prices between two zones
         * @description The heart of Itafika. Given an origin, destination, weight, and package
         *     type, returns every available delivery option across all transport
         *     classes, each with an estimated cost, time, and reliability score.
         */
        post: operations["createQuote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shipments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Lock in a chosen quote and create a shipment
         * @description Accepts a quote the customer selected, records the shipment, generates a
         *     tracking ID, and notifies the relevant adapter. In Phase 1 the booking is
         *     recorded but provider dispatch may be a stub depending on the adapter.
         */
        post: operations["createShipment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shipments/{tracking_id}/track": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the unified tracking status of a shipment
         * @description Returns the shipment's current universal status and its history.
         *     Every provider's own states are normalised into Itafika's five
         *     universal statuses.
         */
        get: operations["trackShipment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description The kind of location.
         * @enum {string}
         */
        ZoneType: "cbd_hub" | "stage" | "residential_area";
        /**
         * @description The class of transport. Adapters are organised by these classes.
         * @enum {string}
         */
        ProviderType: "boda_rider" | "matatu_sacco" | "bus" | "national_courier";
        /**
         * @description The five universal shipment statuses.
         * @enum {string}
         */
        TrackingStatus: "package_picked" | "in_transit" | "at_sorting_hub" | "ready_for_pickup" | "delivered";
        Coordinates: {
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
        };
        Zone: {
            /** @description Stable, human-readable identifier, e.g. ZONE_NBI_CBD_01. */
            id: string;
            /** @description Human-readable name, e.g. "RNG Plaza". */
            name: string;
            type: components["schemas"]["ZoneType"];
            /** @description The town or city the zone belongs to. */
            town: string;
            coordinates?: components["schemas"]["Coordinates"];
        };
        QuoteRequest: {
            origin_zone_id: string;
            destination_zone_id: string;
            /**
             * Format: double
             * @description Package weight in kilograms.
             */
            package_weight_kg: number;
            /** @description Free-form category, e.g. "apparel", "documents", "electronics". */
            package_type?: string;
        };
        Quote: {
            /** @description Opaque ID used to book this quote via POST /v1/shipments. */
            quote_id: string;
            provider_type: components["schemas"]["ProviderType"];
            /** @description Human-readable provider name shown to the customer. */
            provider_name: string;
            /** @description Estimated cost in Kenyan Shillings. */
            estimated_cost_kes: number;
            /** @description Human-readable estimate, e.g. "45 mins", "3 hours", "next day". */
            estimated_time: string;
            /**
             * Format: double
             * @description 0–1 confidence in on-time, intact delivery.
             */
            reliability_score?: number;
        };
        Contact: {
            name: string;
            /** @description E.164 format, e.g. +254712345678. */
            phone: string;
        };
        ShipmentRequest: {
            quote_id: string;
            sender: components["schemas"]["Contact"];
            recipient: components["schemas"]["Contact"];
            package_description?: string;
        };
        Shipment: {
            /** @description Use with GET /v1/shipments/{tracking_id}/track. */
            tracking_id: string;
            status: components["schemas"]["TrackingStatus"];
            quote?: components["schemas"]["Quote"];
            sender?: components["schemas"]["Contact"];
            recipient?: components["schemas"]["Contact"];
            /** Format: date-time */
            created_at: string;
        };
        TrackingEvent: {
            status: components["schemas"]["TrackingStatus"];
            /** Format: date-time */
            at: string;
            note?: string;
        };
        TrackingResponse: {
            tracking_id: string;
            status: components["schemas"]["TrackingStatus"];
            history: components["schemas"]["TrackingEvent"][];
        };
        Error: {
            error: {
                code: string;
                message: string;
            };
        };
    };
    responses: {
        /** @description The request was malformed or failed validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "invalid_request",
                 *         "message": "package_weight_kg must be a positive number"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listZones: {
        parameters: {
            query?: {
                /** @description Filter by zone type. */
                type?: components["schemas"]["ZoneType"];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of zones. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "zones": [
                     *         {
                     *           "id": "ZONE_NBI_CBD_01",
                     *           "name": "RNG Plaza",
                     *           "type": "cbd_hub",
                     *           "town": "Nairobi",
                     *           "coordinates": {
                     *             "lat": -1.2841,
                     *             "lng": 36.8255
                     *           }
                     *         },
                     *         {
                     *           "id": "ZONE_NKR_MAIN",
                     *           "name": "Nakuru Main Stage",
                     *           "type": "stage",
                     *           "town": "Nakuru",
                     *           "coordinates": {
                     *             "lat": -0.3031,
                     *             "lng": 36.08
                     *           }
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": {
                        zones?: components["schemas"]["Zone"][];
                    };
                };
            };
        };
    };
    searchZones: {
        parameters: {
            query: {
                /** @description Free-text query, e.g. "cbd", "nyeri", "rng". */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching zones, best match first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        query?: string;
                        zones?: components["schemas"]["Zone"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createQuote: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "origin_zone_id": "ZONE_NBI_CBD_01",
                 *       "destination_zone_id": "ZONE_NKR_MAIN",
                 *       "package_weight_kg": 2.5,
                 *       "package_type": "apparel"
                 *     }
                 */
                "application/json": components["schemas"]["QuoteRequest"];
            };
        };
        responses: {
            /** @description Available quotes. May be an empty list if no provider serves the route. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "origin_zone_id": "ZONE_NBI_CBD_01",
                     *       "destination_zone_id": "ZONE_NKR_MAIN",
                     *       "quotes": [
                     *         {
                     *           "quote_id": "qt_8sd92ka",
                     *           "provider_type": "boda_rider",
                     *           "provider_name": "Independent Rider (CBD Pool)",
                     *           "estimated_cost_kes": 250,
                     *           "estimated_time": "45 mins",
                     *           "reliability_score": 0.92
                     *         },
                     *         {
                     *           "quote_id": "qt_2mn41bq",
                     *           "provider_type": "matatu_sacco",
                     *           "provider_name": "Mololine Sacco",
                     *           "estimated_cost_kes": 400,
                     *           "estimated_time": "3 hours",
                     *           "reliability_score": 0.98
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": {
                        origin_zone_id?: string;
                        destination_zone_id?: string;
                        quotes?: components["schemas"]["Quote"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description One or both zone IDs are unknown. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createShipment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "quote_id": "qt_2mn41bq",
                 *       "sender": {
                 *         "name": "Asha Mwangi",
                 *         "phone": "+254712345678"
                 *       },
                 *       "recipient": {
                 *         "name": "John Otieno",
                 *         "phone": "+254723456789"
                 *       },
                 *       "package_description": "Sealed apparel box, 2.5kg"
                 *     }
                 */
                "application/json": components["schemas"]["ShipmentRequest"];
            };
        };
        responses: {
            /** @description Shipment created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shipment"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description The quote_id is unknown or has expired. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    trackShipment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tracking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current status and history. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "tracking_id": "trk_kf93md2",
                     *       "status": "in_transit",
                     *       "history": [
                     *         {
                     *           "status": "package_picked",
                     *           "at": "2026-06-08T08:14:00Z"
                     *         },
                     *         {
                     *           "status": "in_transit",
                     *           "at": "2026-06-08T08:40:00Z"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["TrackingResponse"];
                };
            };
            /** @description Unknown tracking ID. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
