/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List supported drop-off / pick-up locations */
        get: operations["listZones"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/zones/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search locations by name */
        get: operations["searchZones"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/freshness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List dataset freshness by town */
        get: operations["listFreshness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Browse delivery options into a destination area
         * @description Returns the navigable option tree for the shop's origin into the customer's
         *     town: which providers serve the route, in which mode, where they collect, and
         *     an indicative starting cost. This is **navigation, not pricing** — it takes no
         *     package weight and returns no bookable price. Once the customer picks a
         *     collection point (which becomes the `destination_zone_id`) and the weight is
         *     known, the shop calls `POST /v1/quotes` for the exact, bookable price.
         *
         *     Specified by ADR 0017 (checkout-delivery direction).
         */
        get: operations["listOptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/modes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the transport-mode registry
         * @description Returns the transport modes a customer can choose between, each with display
         *     metadata. The registry is governed reference data (ADR 0019), not a hardcoded
         *     list — a shop can render any mode, including ones added after it was built,
         *     without a code change.
         */
        get: operations["listModes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get delivery options and prices between two zones
         * @description The heart of Itafika. Given an origin, destination, weight, and package
         *     details, returns every available delivery option across all transport
         *     classes, each with an estimated cost, time, and reliability score.
         */
        post: operations["createQuote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Lock in a chosen quote and create a delivery
         * @description Accepts a quote the customer selected, records the delivery, and generates
         *     a tracking ID. In Phase 1 the reference Worker records the booking, while
         *     provider dispatch through adapters remains follow-on integration work.
         */
        post: operations["createDelivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deliveries/{tracking_id}/track": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the unified tracking status of a delivery
         * @description Returns the delivery's current universal status and its history.
         *     Every provider's own states are normalised into Itafika's five
         *     universal statuses.
         */
        get: operations["trackDelivery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deliveries/{tracking_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Append a tracking event to a delivery
         * @description Adds a new event to the delivery's unified tracking history.
         *     In Phase 1 this is a manual/internal update path used before full
         *     adapter-driven or webhook-driven tracking flows exist.
         */
        post: operations["createTrackingEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description The kind of location.
         * @enum {string}
         */
        ZoneType: "cbd_hub" | "stage" | "residential_area";
        /**
         * @description A transport-mode identifier — the "mode" a customer chooses, and how adapters
         *     are grouped. This is an **open identifier drawn from the modes registry**
         *     (`GET /v1/modes`), **not a closed set** (ADR 0019). New modes are added as
         *     governed reference data (`modes.csv`), never by changing this contract or the
         *     engine. The core never branches on a specific value; consumers should render
         *     an unknown mode from the registry's display metadata rather than treating the
         *     examples below as exhaustive.
         *
         *     The seed registry ships with all of these as data rows; `GET /v1/modes` is the
         *     source of truth for what currently exists.
         * @example boda_rider
         * @example matatu_sacco
         * @example bus
         * @example national_courier
         * @example shuttle
         * @example taxi
         * @example cargo_truck
         */
        ProviderType: string;
        /**
         * @description A transport mode in the registry, with display metadata so a shop can render
         *     any mode — including ones added after it was built — without a code change
         *     (ADR 0019).
         */
        Mode: {
            id: components["schemas"]["ProviderType"];
            /** @description Display name shown to customers, e.g. "Shuttle". */
            label: string;
            /** @description One line on what the mode is. */
            description?: string;
        };
        /**
         * @description How the recipient receives the parcel. Specified by ADR 0016
         *     (checkout-delivery direction).
         * @enum {string}
         */
        CollectionType: "office_pickup" | "door_delivery";
        /**
         * @description The five universal delivery statuses.
         * @enum {string}
         */
        TrackingStatus: "package_picked" | "in_transit" | "at_sorting_hub" | "ready_for_pickup" | "delivered";
        Coordinates: {
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
        };
        Zone: {
            /** @description Stable, human-readable identifier, e.g. ZONE_NBI_CBD_01. */
            id: string;
            /** @description Human-readable name, e.g. "RNG Plaza". */
            name: string;
            type: components["schemas"]["ZoneType"];
            /** @description The town or city the zone belongs to. */
            town: string;
            /**
             * @description The county the zone belongs to, the top level of the checkout funnel
             *     (ADR 0017).
             */
            county?: string;
            coordinates?: components["schemas"]["Coordinates"];
        };
        FreshnessEntry: {
            /** @description Town or city name matching the dataset freshness record. */
            town: string;
            /** @description Date when the dataset for this town was last reviewed. */
            last_updated: string;
        };
        QuoteRequest: {
            origin_zone_id: string;
            destination_zone_id: string;
            /**
             * Format: double
             * @description Package weight in kilograms.
             */
            package_weight_kg: number;
            /** @description Optional package category for filtering or ranking logic. Phase 1 implementations may ignore it. */
            package_type?: string;
        };
        Quote: {
            /** @description Opaque ID used to book this quote via POST /v1/deliveries. */
            quote_id: string;
            provider_type: components["schemas"]["ProviderType"];
            /** @description Human-readable provider name shown to the customer. */
            provider_name: string;
            /** @description Estimated cost in Kenyan Shillings. */
            estimated_cost_kes: number;
            /** @description Human-readable estimate, e.g. "45 mins", "3 hours", "next day". */
            estimated_time: string;
            /**
             * Format: double
             * @description 0–1 confidence in on-time, intact delivery.
             */
            reliability_score?: number;
            /**
             * @description How the recipient receives this option's parcel — collect at the
             *     provider's office/stage, or door delivery. Specified by ADR 0016
             *     (checkout-delivery direction).
             */
            collection_type?: components["schemas"]["CollectionType"];
            collection_point?: components["schemas"]["CollectionPoint"];
        };
        /**
         * @description For `office_pickup`, the zone where the recipient collects the parcel. Absent
         *     for `door_delivery`. Specified by ADR 0016 (checkout-delivery direction).
         */
        CollectionPoint: {
            zone_id: string;
            name: string;
            town?: string;
        };
        /**
         * @description A provider+mode the customer can choose for a destination town, with where it
         *     collects and an indicative starting cost. Navigation only — the exact bookable
         *     price comes from POST /v1/quotes. Specified by ADR 0017 (checkout-delivery
         *     direction). `provider_id` is deliberately not exposed (internal column).
         */
        DeliveryOption: {
            provider_name: string;
            provider_type: components["schemas"]["ProviderType"];
            /** Format: double */
            reliability_score?: number;
            collection_type: components["schemas"]["CollectionType"];
            /** @description The zones in the destination town where this provider collects. */
            collection_points?: components["schemas"]["CollectionPoint"][];
            /** @description Indicative starting cost (the route's base cost). Not bookable; get the exact price from POST /v1/quotes. */
            from_cost_kes?: number;
        };
        Contact: {
            name: string;
            /** @description E.164 format, e.g. +254712345678. */
            phone: string;
            /**
             * @description Optional national ID asked for at an office/stage parcel desk on
             *     collection. Specified by ADR 0018 (checkout-delivery direction).
             */
            id_number?: string;
        };
        DeliveryRequest: {
            quote_id: string;
            sender: components["schemas"]["Contact"];
            recipient: components["schemas"]["Contact"];
            /** @description What is in the box (distinct from handover instructions). */
            package_description?: string;
            /**
             * @description Handover instructions, e.g. "Call before handover; give to Achieng
             *     (sister)." Specified by ADR 0018 (checkout-delivery direction).
             */
            instructions?: string;
            /**
             * @description Someone other than the recipient authorised to collect. Specified by
             *     ADR 0018 (checkout-delivery direction).
             */
            alternate_collector?: components["schemas"]["Contact"];
        };
        Delivery: {
            /** @description Use with GET /v1/deliveries/{tracking_id}/track. */
            tracking_id: string;
            status: components["schemas"]["TrackingStatus"];
            quote: components["schemas"]["Quote"];
            sender: components["schemas"]["Contact"];
            recipient: components["schemas"]["Contact"];
            /**
             * @description Handover instructions recorded at booking. Specified by ADR 0018
             *     (checkout-delivery direction).
             */
            instructions?: string;
            /** Format: date-time */
            created_at: string;
        };
        TrackingEvent: {
            status: components["schemas"]["TrackingStatus"];
            /** Format: date-time */
            at: string;
            note?: string;
        };
        TrackingEventCreateRequest: {
            status: components["schemas"]["TrackingStatus"];
            note?: string;
        };
        TrackingResponse: {
            tracking_id: string;
            status: components["schemas"]["TrackingStatus"];
            history: components["schemas"]["TrackingEvent"][];
        };
        Error: {
            error: {
                code: string;
                message: string;
            };
        };
    };
    responses: {
        /** @description The request was malformed or failed validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "invalid_request",
                 *         "message": "package_weight_kg must be a positive number"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listZones: {
        parameters: {
            query?: {
                /** @description Filter by zone type. */
                type?: components["schemas"]["ZoneType"];
                /** @description Filter by town (ADR 0017). */
                town?: string;
                /** @description Filter by county (the checkout funnel's top level; ADR 0017). */
                county?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of zones. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "zones": [
                     *         {
                     *           "id": "ZONE_NBI_CBD_01",
                     *           "name": "RNG Plaza",
                     *           "type": "cbd_hub",
                     *           "town": "Nairobi",
                     *           "coordinates": {
                     *             "lat": -1.2841,
                     *             "lng": 36.8255
                     *           }
                     *         },
                     *         {
                     *           "id": "ZONE_NKR_MAIN",
                     *           "name": "Nakuru Main Stage",
                     *           "type": "stage",
                     *           "town": "Nakuru",
                     *           "coordinates": {
                     *             "lat": -0.3031,
                     *             "lng": 36.08
                     *           }
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": {
                        zones?: components["schemas"]["Zone"][];
                    };
                };
            };
        };
    };
    searchZones: {
        parameters: {
            query: {
                /** @description Free-text query, e.g. "cbd", "nyeri", "rng". */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching zones, best match first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "zones": [
                     *         {
                     *           "id": "ZONE_NBI_CBD_01",
                     *           "name": "RNG Plaza",
                     *           "type": "cbd_hub",
                     *           "town": "Nairobi"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": {
                        zones?: components["schemas"]["Zone"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    listFreshness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The last-reviewed date for each town currently loaded in the dataset. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "freshness": [
                     *         {
                     *           "town": "Nairobi",
                     *           "last_updated": "2026-06-08"
                     *         },
                     *         {
                     *           "town": "Nakuru",
                     *           "last_updated": "2026-06-08"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": {
                        freshness?: components["schemas"]["FreshnessEntry"][];
                    };
                };
            };
        };
    };
    listOptions: {
        parameters: {
            query: {
                /** @description The shop's pickup zone. */
                origin_zone_id: string;
                /** @description The customer's town. */
                destination_town: string;
                /** @description Filter to a single transport mode. */
                mode?: components["schemas"]["ProviderType"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available delivery options into the town. May be an empty list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "origin_zone_id": "ZONE_NBI_CBD_01",
                     *       "destination_town": "Nyeri",
                     *       "options": [
                     *         {
                     *           "provider_name": "2NK Sacco",
                     *           "provider_type": "shuttle",
                     *           "reliability_score": 0.95,
                     *           "collection_type": "office_pickup",
                     *           "from_cost_kes": 300,
                     *           "collection_points": [
                     *             {
                     *               "zone_id": "ZONE_NYR_STG_01",
                     *               "name": "2NK Nyeri Town Office"
                     *             }
                     *           ]
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": {
                        origin_zone_id?: string;
                        destination_town?: string;
                        options?: components["schemas"]["DeliveryOption"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    listModes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The transport modes currently in the dataset. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "modes": [
                     *         {
                     *           "id": "matatu_sacco",
                     *           "label": "Matatu SACCO",
                     *           "description": "Shared-taxi SACCO parcel desk service."
                     *         },
                     *         {
                     *           "id": "shuttle",
                     *           "label": "Shuttle",
                     *           "description": "Scheduled long-distance shuttle SACCOs, e.g. 2NK, North Rift."
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": {
                        modes?: components["schemas"]["Mode"][];
                    };
                };
            };
        };
    };
    createQuote: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "origin_zone_id": "ZONE_NBI_CBD_01",
                 *       "destination_zone_id": "ZONE_NKR_MAIN",
                 *       "package_weight_kg": 2.5
                 *     }
                 */
                "application/json": components["schemas"]["QuoteRequest"];
            };
        };
        responses: {
            /** @description Available quotes. May be an empty list if no provider serves the route. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "origin_zone_id": "ZONE_NBI_CBD_01",
                     *       "destination_zone_id": "ZONE_NKR_MAIN",
                     *       "quotes": [
                     *         {
                     *           "quote_id": "qt_8f3b4d2a91c4e87ab11d42ef",
                     *           "provider_type": "boda_rider",
                     *           "provider_name": "Independent Rider (CBD Pool)",
                     *           "estimated_cost_kes": 250,
                     *           "estimated_time": "45 mins",
                     *           "reliability_score": 0.92
                     *         },
                     *         {
                     *           "quote_id": "qt_b1a56ce02d7345f398ee2c04",
                     *           "provider_type": "matatu_sacco",
                     *           "provider_name": "Mololine Sacco",
                     *           "estimated_cost_kes": 400,
                     *           "estimated_time": "3 hours",
                     *           "reliability_score": 0.98
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": {
                        origin_zone_id?: string;
                        destination_zone_id?: string;
                        quotes?: components["schemas"]["Quote"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description One or both zone IDs are unknown. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createDelivery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "quote_id": "qt_b1a56ce02d7345f398ee2c04",
                 *       "sender": {
                 *         "name": "Asha Mwangi",
                 *         "phone": "+254712345678"
                 *       },
                 *       "recipient": {
                 *         "name": "John Otieno",
                 *         "phone": "+254723456789"
                 *       },
                 *       "package_description": "Sealed apparel box, 2.5kg"
                 *     }
                 */
                "application/json": components["schemas"]["DeliveryRequest"];
            };
        };
        responses: {
            /** @description Delivery created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Delivery"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description The quote_id is unknown or has expired. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    trackDelivery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tracking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current status and history. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "tracking_id": "trk_7f93f6f7a86c4f5188ff8d5d9c6f2b47",
                     *       "status": "in_transit",
                     *       "history": [
                     *         {
                     *           "status": "package_picked",
                     *           "at": "2026-06-08T08:14:00Z"
                     *         },
                     *         {
                     *           "status": "in_transit",
                     *           "at": "2026-06-08T08:40:00Z"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["TrackingResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Unknown tracking ID. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createTrackingEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tracking_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "status": "in_transit",
                 *       "note": "Handed over to linehaul driver at Nairobi stage"
                 *     }
                 */
                "application/json": components["schemas"]["TrackingEventCreateRequest"];
            };
        };
        responses: {
            /** @description Event recorded and tracking state updated. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackingResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Unknown tracking ID. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Status regression is not allowed. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
